import {describe,expect,it} from "vitest";
import {flowPerMonth,indexLevel,percentRate,scorePoint,share01,stockLevel,type ConfigSnapshot,type EconomyState,type IndustryId} from "@macro-nation/domain";
import {updateFiscalIndustries} from "./index";
function economy():EconomyState{
 const industries=Object.fromEntries(["agricultureResources","manufacturing","construction","householdServices","financeRealEstate","energyLogistics"].map(id=>[id,{productionIndex:indexLevel(100),employmentShare:share01(1/6),capacityIndex:indexLevel(100),importDependency:share01(.2),priceIndex:indexLevel(100)}])) as Record<IndustryId,EconomyState["industries"][IndustryId]>;
 return {indices:{realGdp:indexLevel(100),cpi:indexLevel(100),fx:indexLevel(100),nominalWage:indexLevel(100),realHouseholdIncome:indexLevel(100),potentialGdp:indexLevel(100),importPrice:indexLevel(100)},rates:{inflationAnnual:percentRate(.02),unemployment:percentRate(.05),policyRate:percentRate(.02),marketRate:percentRate(.025),expectedInflation:percentRate(.02),foreignRate:percentRate(.025)},ratios:{governmentDebtRatio:percentRate(.9),fiscalBalanceRatio:percentRate(-.03)},flows:{consumption:flowPerMonth(60),investment:flowPerMonth(18),governmentConsumption:flowPerMonth(20),publicInvestment:flowPerMonth(4),exports:flowPerMonth(25),imports:flowPerMonth(23),taxRevenue:flowPerMonth(28),primarySpending:flowPerMonth(30),interestPayment:flowPerMonth(2),currentAccount:flowPerMonth(2),capitalFlow:flowPerMonth(0)},stocks:{governmentDebt:stockLevel(1080),domesticGovernmentDebt:stockLevel(800),externalGovernmentDebt:stockLevel(280),foreignReserves:stockLevel(300)},sentiment:{consumerConfidence:scorePoint(50),businessConfidence:scorePoint(50),policyTrust:scorePoint(60),support:scorePoint(55),inequality:scorePoint(40),speculationPressure:scorePoint(20)},institutions:{politicalCapital:scorePoint(60),implementationCapacity:scorePoint(65),centralBankIndependence:scorePoint(80),taxCapacity:scorePoint(70),procurementTransparency:scorePoint(70)},industries,infrastructure:{transport:indexLevel(100),energy:indexLevel(100),digital:indexLevel(100),water:indexLevel(100),publicFacilities:indexLevel(100)},external:{foreignGrowthAnnual:percentRate(.025),foreignRateAnnual:percentRate(.025),resourcePriceIndex:indexLevel(100),partnerRelations:scorePoint(60),disasterAlert:scorePoint(20),fxShockLogIndex:0 as EconomyState["external"]["fxShockLogIndex"]}};
}
function config():ConfigSnapshot{return {snapshotVersion:"t",configHash:"a".repeat(64),sourceManifest:[],normalizedConfig:{parameters:{"CORE-GROW-001":.018,"CORE-INF-001":.02,"CORE-U-001":.05,"DEBT-REPRICE-001":.015,"FISC-TAX-ELAS-001":1,"RISK-DEBT-001":.015,"RISK-TRUST-001":.01,"TRUST-MR-001":.05,"TRUST-ANCHOR-001":60,"TRUST-INF-001":4,"TRUST-U-001":3,"TRUST-DEBT-001":.5,"POLCAP-TRUST-001":.08,"IND-GDP-001":.8,"IND-CAP-001":.02,"LT-POP-001":.005,"LT-INFRA-001":.002}}}}
describe("fiscal trust and industries",()=>{
 it("preserves the monthly debt stock-flow identity",()=>{const e=economy(),r=updateFiscalIndustries({economy:e,effects:[],monthIndex:0,configSnapshot:config()});expect(r.economy.stocks.governmentDebt).toBeCloseTo(e.stocks.governmentDebt+r.economy.flows.primarySpending-r.economy.flows.taxRevenue+r.economy.flows.interestPayment,10);expect(r.economy.stocks.domesticGovernmentDebt+r.economy.stocks.externalGovernmentDebt).toBeCloseTo(r.economy.stocks.governmentDebt,10);});
 it("keeps the weighted six-industry production aggregate equal to real GDP",()=>{const r=updateFiscalIndustries({economy:economy(),effects:[],monthIndex:0,configSnapshot:config()});const aggregate=Object.values(r.economy.industries).reduce((s,x)=>s+x.productionIndex*x.employmentShare,0);expect(aggregate).toBeCloseTo(r.economy.indices.realGdp,10);});
 it("clamps trust and exposes long-term hooks",()=>{const e=economy();const r=updateFiscalIndustries({economy:{...e,sentiment:{...e.sentiment,policyTrust:scorePoint(0)}},effects:[],monthIndex:0,configSnapshot:config()});expect(r.economy.sentiment.policyTrust).toBeGreaterThanOrEqual(0);expect(r.longTermHooks.productivityGrowthAnnual).toBe(.018);});
});
